export const PRESETS = [
  {
    name: "Classic GameBoy",
    colorBack: "#0f380f",
    colorFront: "#8bac0f",
    colorHighlight: "#9bbc0f",
    originalColors: false,
    type: "4x4",
    size: 3,
    colorSteps: 4,
    brightness: 0,
    contrast: 0.1,
    gamma: 1.0,
  },
  {
    name: "Cyberpunk Glow",
    colorBack: "#0c051a",
    colorFront: "#ff007f",
    colorHighlight: "#00ffff",
    originalColors: false,
    type: "8x8",
    size: 2,
    colorSteps: 3,
    brightness: 0.05,
    contrast: 0.2,
    gamma: 1.1,
  },
  {
    name: "1-Bit Noir",
    colorBack: "#000000",
    colorFront: "#ffffff",
    colorHighlight: "#ffffff",
    originalColors: false,
    type: "8x8",
    size: 1.5,
    colorSteps: 2,
    brightness: 0,
    contrast: 0.3,
    gamma: 1.2,
  },
  {
    name: "Amber Terminal",
    colorBack: "#1a0f00",
    colorFront: "#ffb000",
    colorHighlight: "#ffb000",
    originalColors: false,
    type: "4x4",
    size: 2.5,
    colorSteps: 2,
    brightness: 0.1,
    contrast: 0.2,
    gamma: 1.0,
  },
  {
    name: "80s Synthwave",
    colorBack: "#200030",
    colorFront: "#ff00aa",
    colorHighlight: "#ffea00",
    originalColors: false,
    type: "8x8",
    size: 2,
    colorSteps: 4,
    brightness: 0,
    contrast: 0.15,
    gamma: 1.0,
  },
  {
    name: "True Color Dither",
    colorBack: "#000000",
    colorFront: "#ffffff",
    colorHighlight: "#ffffff",
    originalColors: true,
    type: "8x8",
    size: 2,
    colorSteps: 6,
    brightness: 0,
    contrast: 0,
    gamma: 1.0,
  }
];
